baseurl: "https://nothingradical.blog"
languageCode: "en-us"
paginate: 5
title: "Nothing Radical"
copyright: "Â© 2020-2022 Frawley CC BY-NC-ND 4.0"
enableRobotsTXT: true

author:
  name: "Frawley"
  email: "frawleyskid@gmail.com"

outputs:
  home: ["HTML", "RSS", "HEADERS"]

outputFormats:
  RSS:
    mediaType: "application/rss+xml"
    baseName: "feed"
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

mediaTypes:
  text/netlify:
    suffixes: []
  application/rss+xml:
    suffixes: []
